from .inspector_repository import select_all
from .inspector_repository import select_inspector_by_email
from .inspector_repository import create_inspector, delete_inspector
from .provincia_repository import select_all, create_provincia, select_provincia_by_nombre
from .municipio_repository import select_all, create_municipio, select_municipio_by_nombre
from .organismo_repository import select_all,create_organismo,select_organismo_by_nombre
from .entidad_repository import select_all,create_entidad,select_entidad_by_nombre,get_nombre_organismo_by_entidad_nombre,get_organismo_by_entidad_nombre
from .establecimiento_repository import select_all, create_establecimiento, select_establecimiento_by_nombre,select_establecimientos_by_entidad,select_establecimientos_by_municipio,delete_establecimiento
from .norma_repository import select_all, create_norma,select_norma_by_codigo, delete_norma
from .inspeccion_repository import  select_all_inspecciones, select_inspeccion_by_codigo,select_inspecciones_by_inspectores,select_inspecciones_by_month,create_inspeccion,update_inspeccion,delete_inspeccion,select_inspecciones_with_infraccion, select_inspecciones_with_infraccion_producto_servicio,select_inspecciones_with_infraccion_higiene,select_inspecciones_with_infraccion_metrologia,select_inspecciones_without_infraccion, select_inspecciones_by_organismo
from .oblig_hacer_repository import select_all_obligaciones, select_obligacion_by_codigo, select_obligaciones_by_inspeccion, update_obligacion_hacer,select_obligaciones_by_resultado
from .tabs_reposiroty import create_informe, create_inspeccion,update_obligacion_hacer